default: &default
  adapter: postgresql
  encoding: unicode
  username: etg
  password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: automated_testing_development

test:
  <<: *default
  database: automated_testing_test

production:
  <<: *default
  database: automated_testing_production
  username: automated_testing
  password: <%= ENV["AUTOMATED_TESTING_DATABASE_PASSWORD"] %>
